#!D:\MLOPS TRAINING SESSIOINS\Wednesday 11,2023\Flight Price Prediction\Flight Price Prediction\.virtualenvs\flight_price_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
