stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - source_code/test_data.csv
    - source_code/train_data.csv

    outs:
    - data/raw/flight_train.csv
    - data/raw/flight_test.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    dep:
    - src/split_data.py
    - data/raw/flight_train.csv
    - data/raw/flight_test.csv

    outs:
    - data/processed/flight_train_processed.csv
    - data/processed/flight_test_processed.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/flight_train_processed.csv
    - data/processed/flight_test_processed.csv
    - src/train_and_evaluate.py

    params:
    - estimators.RandomForestRegressor.params.max_depth

    metrics:
    - reports/params.json
      cache: false
    - reports/scores.json
      cache: false
    
    outs:
    - models/model.joblib
    