base:
  project: Flight Price Prediction
  random_state: 42
  target_col: Price

data_source:
  s3_source:
    train_data: source_code/train_data.csv
    test_data: source_code/test_data.csv

load_data:
  raw_train_dataset_csv: data/raw/flight_train.csv


split_data:
  train_path: data/processed/flight_train_processed.csv
  test_path:  data/processed/flight_test_processed.csv
  test_size: 0.2



estimators:
  RandomForestRegressor:
    params:
      max_depth: 3


model_dir: models


reports:
  params: reports/params.json
  scores: reports/scores.json


webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: RandomForestRegressor_Experiment
  run_name: mlops
  registered_model_name: RandomForestFlightPrice
  remote_server_uri: http://127.0.0.1:5000/